language: node_js
before_install: npm install -g npm@'>=2.13.5'
node_js:
- '0.10'
- '0.12'
- '4.0'
- '4.1'
- '4.2'
- '5.0'
- '5.1'
- iojs
before_script:
- npm install -g grunt-cli
notifications:
  email: false
deploy:
  provider: npm
  email: addons-dev-automation+npm@mozilla.com
  api_key:
    secure: eaHxNEy0RXK4An1vqZo2x0X/zSAwEQeMgtt82G+NffJIesM9023AZ+N0ZITfSzKz9JpM0+H0O12vm4ze/6jEooax1Bp39dgde8a3ahCZQ187Se4ZUg3k6SF4SEO9DfCYu/TSJCNr1N3B/FycgCSui4kqcCLNlzRtrRdKi5Rl0tQ=
  on:
    tags: true
    repo: mozilla/grunt-i18n-abide
